export default {
  banner: {
    variant: "banner",
    content_justify: "left",
    content_bg_color: false,
    bg_tint: "primary-light-x",
    background_image_url: "https://picsum.photos/id/41/900/500",
    card_data: {
      variant: "default",
      first_component: true,
      media: false,
      heading: "Hero Heading",
      text: "<p>Lorem ipsum dolor sit amet consectetur adipiscing elit consequat, pellentesque accumsan metus sed fusce fringilla pretium varius euismod.</p>",
      button_data: {
        label: "Text Button",
        href: "#",
        variant: "text",
      },
    },
  },
  banner_mega: {
    variant: "mega",
    content_justify: "left",
    content_bg_color: false,
    bg_tint: "primary-light-x",
    background_image_url: "https://picsum.photos/id/41/900/500",
    card_data: {
      variant: "default",
      first_component: true,
      media: false,
      heading: "Hero Heading",
      text: "<p>Lorem ipsum dolor sit amet consectetur adipiscing elit consequat, pellentesque accumsan metus sed fusce fringilla pretium varius euismod.</p><div class='header-search__wrapper'><div class='cluster header-search header-search--no-toggle bg-transparent'><form action='/search' class='header-search__form' role='search'><label class='sr-only' for='header-search'>Search</label> <input id='header-search' name='search' placeholder='Search' type='search'/> <button class='header-search__icon' type='submit'><div class='icon-wrapper icon-wrapper--fa-search'><svg class='icon' aria-labelledby=''><use xlink:href='/icons.svg#fa-search'></use></svg><span class='sr-only'>Search</span></div></button></form></div></div>",
    },
  },
  banner_featured_links: {
    variant: "banner",
    content_justify: "left",
    content_bg_color: false,
    bg_tint: "primary-light-x",
    background_image_url: "https://picsum.photos/id/41/900/500",
    card_data: {
      variant: "default",
      first_component: true,
      media: false,
      heading: "Hero Heading",
      text: "<p>Lorem ipsum dolor sit amet consectetur adipiscing elit consequat, pellentesque accumsan metus sed fusce fringilla pretium varius euismod.</p>",
      button_data: {
        label: "Text Button",
        href: "#",
        variant: "text",
      },
    },
    navigation: [
      {
        variant: "striped-aligned",
        clickable_card: true,
        background: null,
        aspect: [],
        media: false,
        icon_data: {
          icon: "line-paper-gather-documents",
          color: false,
        },
        heading: "Case Information",
        text: "",
        button_data: [
          {
            label: "Button",
            href: "#",
            variant: "primary",
          },
        ],
      },
      {
        variant: "striped-aligned",
        clickable_card: true,
        background: null,
        aspect: [],
        media: false,
        icon_data: {
          icon: "line-judge-gavel",
          color: false,
        },
        heading: "Oral Arguments",
        text: "",
        button_data: [
          {
            label: "Button",
            href: "#",
            variant: "primary",
          },
        ],
      },
      {
        variant: "striped-aligned",
        clickable_card: true,
        background: null,
        aspect: [],
        media: false,
        icon_data: {
          icon: "line-circle-person",
          color: false,
        },
        heading: "Job Opportunities",
        text: "",
        button_data: [
          {
            label: "Button",
            href: "#",
            variant: "primary",
          },
        ],
      },
      {
        variant: "striped-aligned",
        clickable_card: true,
        background: null,
        aspect: [],
        media: false,
        icon_data: {
          icon: "line-courthouse",
          color: false,
        },
        heading: "About the Courts",
        text: "",
        button_data: [
          {
            label: "Button",
            href: "#",
            variant: "primary",
          },
        ],
      },
    ],
  },
  content_bg: {
    variant: "content-bg",
    content_justify: "left",
    content_bg_color: "white",
    bg_tint: false,
    background_image_url: "https://picsum.photos/id/41/900/500",
    first_component: true,
    card_data: {
      variant: "default",
      first_component: true,
      media: false,
      heading: "Hero Heading",
      text: "<p>varius euismod.</p>",
      button_data: {
        label: "Text Button",
        href: "#",
        variant: "text",
      },
    },
  },
};
