import Card from "../Card/Card.twig";

export default {
  default: {
    hangover_hide_compact: false,
    hangover_offset: 22,
    background: null,
    brow: false,
    heading: "This is a Heading",
    text: "",
    hangover_content: "",
    bottom_content: "",
    blurb: false,
  },
  with_brow: {
    hangover_hide_compact: false,
    hangover_offset: 22,
    background: null,
    brow: {
      variant: "default",
      part_one: "Brow Example",
      part_two: "Part two",
    },
    heading: "This is a Heading",
    text: "",
    hangover_content: "",
    bottom_content: "",
    blurb: false,
  },
  with_media: {
    hangover_hide_compact: false,
    hangover_offset: 22,
    background: null,
    brow: {
      variant: "default",
      part_one: "Brow Example",
      part_two: "Part two",
    },
    heading: "This is a Heading",
    text: "",
    hangover_content: Card({
      variant: "bordered-center",
      aspect: [4, 3],
      clickable_card: false,
      background: null,
      media: '<img src="https://source.unsplash.com/random/720x720/?zen" />',
    }),
    bottom_content: "",
    blurb: false,
  },
  with_blurb: {
    hangover_hide_compact: false,
    hangover_offset: 22,
    background: null,
    brow: {
      variant: "default",
      part_one: "Brow Example",
      part_two: "Part two",
    },
    heading: "This is a Heading",
    text: "",
    hangover_content: Card({
      variant: "bordered-center",
      aspect: [4, 3],
      clickable_card: false,
      background: null,
      text: '<h3>Apply or Nominate a Member</h3><p>Lorem, ipsum dolor sit amet consectetur adipisicing elit.</p><p><a href="#" class="button button--primary button--normal">Apply</a></p>',
    }),
    bottom_content: "",
    blurb: true,
  },
  with_text: {
    hangover_hide_compact: false,
    hangover_offset: 22,
    background: null,
    brow: {
      variant: "default",
      part_one: "Brow Example",
      part_two: "Part two",
    },
    heading: "This is a Heading",
    text: "<p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quo autem et libero nulla, maiores quam eaque dolorum architecto cupiditate mollitia praesentium rem, fugiat natus beatae odio dignissimos, aliquam similique ea.</p>",
    hangover_content: Card({
      variant: "bordered-center",
      aspect: [4, 3],
      clickable_card: false,
      background: null,
      media: '<img src="https://source.unsplash.com/random/1280x720/?zen" />',
    }),
    bottom_content: "",
    blurb: false,
  },
  news_header: {
    hangover_hide_compact: false,
    hangover_offset: 22,
    brow: {
      variant: "default_with_date",
      part_one: "Brow Example",
      part_two: "Part two",
      news_header: true,
    },
    heading: "This is a Heading",
    news_header: true,
    text: "<p>Lorem, ipsum dolor sit amet consectetur adipisicing elit.</p>",
    hangover_content: Card({
      variant: "media-right",
      aspect: [],
      clickable_card: false,
      media: '<img src="https://source.unsplash.com/random/1280x720/?zen" />',
    }),
    bottom_content: "",
    blurb: false,
    background: 'striped-base-light-xx',
  },
  with_print: {
    hangover_hide_compact: false,
    hangover_offset: 22,
    brow: {
      variant: "default_with_date",
      part_one: "Brow Example",
    },
    heading: "This is a Heading",
    news_header: true,
    text: "<p>Lorem, ipsum dolor sit amet consectetur adipisicing elit.</p>",
    bottom_content: "",
    blurb: false,
    background: 'striped-base-light-xx',
    share: {
      print_url: 'javascript: window.print();',
      print_aria_label: 'Print advisory body',
    },
  },
  with_bottom: {
    hangover_hide_compact: false,
    hangover_offset: 22,
    background: null,
    brow: {
      variant: "default",
      part_one: "Brow Example",
      part_two: "Part two",
    },
    heading: "This is a Heading",
    text: "<p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quo autem et libero nulla, maiores quam eaque dolorum architecto cupiditate mollitia praesentium rem, fugiat natus beatae odio dignissimos, aliquam similique ea.</p>",
    hangover_content: Card({
      variant: "bordered-center",
      aspect: [4, 3],
      clickable_card: false,
      background: null,
      media: '<img src="https://source.unsplash.com/random/1280x720/?zen" />',
    }),
    bottom_content: "<p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quo autem et libero nulla, maiores quam eaque dolorum architecto cupiditate mollitia praesentium rem, fugiat natus beatae odio dignissimos, aliquam similique ea.</p>",
    blurb: false,
  },
  hide_media_compact: {
    hangover_hide_compact: true,
    hangover_offset: 22,
    background: null,
    brow: {
      variant: "default",
      part_one: "Brow Example",
      part_two: "Part two",
    },
    heading: "This is a Heading",
    text: "<p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quo autem et libero nulla.</p>",
    hangover_content: Card({
      variant: "bordered-center",
      aspect: [4, 3],
      clickable_card: false,
      background: null,
      media: '<img src="https://source.unsplash.com/random/1280x720/?zen" />',
      heading: false,
      text: false,
    }),
    bottom_content: "<p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quo autem et libero nulla, maiores quam eaque dolorum architecto cupiditate mollitia praesentium rem, fugiat natus beatae odio dignissimos, aliquam similique ea.</p>",
    blurb: false,
  },
}
