import drupalAttribute from 'drupal-attribute'

export default {
  default: {
    variant: 'default',
    first_component: false,
    brow_data: {
      variant: "default",
      part_one: "Brow Example",
      part_two: "",
      attributes: new drupalAttribute(),
    },
    heading: 'Heading Example',
    text: '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam lobortis arcu lacus, et facilisis orci facilisis ut.</p>',
    button_data: {
      label: "Button",
      href: "#",
      variant: "primary",
    },
    sub_component_template: null,
    sub_component_data: '<div class="center stack"><h3>Heading</h3><p>Some markup  goes in this space.</p></div><div class="center stack"><h3>Heading</h3><p>Some markup  goes in this space.</p></div>',
    attributes: new drupalAttribute(),
  },
  primary_dark_xx: {
    variant: 'primary-dark-xx',
    first_component: false,
    brow_data: {
      variant: "default",
      part_one: "Brow Example",
      part_two: "",
      attributes: new drupalAttribute(),
    },
    heading: 'Heading Example',
    text: '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam lobortis arcu lacus, et facilisis orci facilisis ut.</p>',
    button_data: {
      label: "Button",
      href: "#",
      variant: "primary",
    },
    sub_component_template: null,
    sub_component_data: '<div class="container"><div class="box" style="background: var(--color-base-light-x)">Sub Component goes here.</div></div>',
    attributes: new drupalAttribute(),
  },
  primary_dark_xx_stripe: {
    variant: 'primary-dark-xx-stripe',
    first_component: false,
    brow_data: {
      variant: "default",
      part_one: "Brow Example",
      part_two: "",
      attributes: new drupalAttribute(),
    },
    heading: 'Heading Example',
    text: '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam lobortis arcu lacus, et facilisis orci facilisis ut.</p>',
    button_data: {
      label: "Button",
      href: "#",
      variant: "primary",
    },
    sub_component_template: null,
    sub_component_data: '<div class="container"><div class="box" style="background: var(--color-base-light-x)">Sub Component goes here.</div></div>',
    attributes: new drupalAttribute(),
  },
  warm_dark_x: {
    variant: 'warm-dark-x',
    first_component: false,
    brow_data: {
      variant: "default",
      part_one: "Brow Example",
      part_two: "",
      attributes: new drupalAttribute(),
    },
    heading: 'Heading Example',
    text: '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam lobortis arcu lacus, et facilisis orci facilisis ut.</p>',
    button_data: {
      label: "Button",
      href: "#",
      variant: "primary",
    },
    sub_component_template: null,
    sub_component_data: '<div class="container"><div class="box" style="background: var(--color-base-light-x)">Sub Component goes here.</div></div>',
    attributes: new drupalAttribute(),
  },
  white: {
    variant: 'white',
    first_component: false,
    brow_data: {
      variant: "default",
      part_one: "Brow Example",
      part_two: "",
      attributes: new drupalAttribute(),
    },
    heading: 'Heading Example',
    text: '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam lobortis arcu lacus, et facilisis orci facilisis ut.</p>',
    button_data: {
      label: "Button",
      href: "#",
      variant: "primary",
    },
    sub_component_template: null,
    sub_component_data: '<div class="container"><div class="box" style="background: var(--color-base-light-x)">Sub Component goes here.</div></div>',
    attributes: new drupalAttribute(),
  },
  bg_image: {
    variant: 'default',
    first_component: false,
    bg_tint: "accent-warm-dark-xx",
    background_image_url: "https://source.unsplash.com/random/900×700/?office,people",
    brow_data: {
      variant: "default",
      part_one: "Brow Example",
      part_two: "",
      attributes: new drupalAttribute(),
    },
    heading: 'Heading Example',
    text: '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam lobortis arcu lacus, et facilisis orci facilisis ut.</p>',
    button_data: {
      label: "Button",
      href: "#",
      variant: "secondary",
    },
    sub_component_template: null,
    sub_component_data: '<div class=""><div class="box" style="background: var(--color-base-light-x)">Sub Component goes here.</div></div>',
    section_layout: 'switcher',
    attributes: new drupalAttribute(),
  },

}
